### ISSUE TITLE
Misleading error for authentication issues with VCD

### ISSUE THREAD

**Issue by tschoergez** [tschoergez/vcenter-event-broker-appliance#10]
When VCD Stream cannot connect to VCD (e.g. due to wrong credentials), nil pointer reference error occurs.
Fix to get a proper error message 
API server listening at: 127.0.0.1:30595

 _    ____  ___                            ______                 __     ____              __           
| |  / /  |/  /      ______ _________     / ____/   _____  ____  / /_   / __ \____  __  __/ /____  _____
| | / / /|_/ / | /| / / __  / ___/ _ \   / __/ | | / / _ \/ __ \/ __/  / /_/ / __ \/ / / / __/ _ \/ ___/
| |/ / /  / /| |/ |/ / /_/ / /  /  __/  / /___ | |/ /  __/ / / / /_   / _, _/ /_/ / /_/ / /_/  __/ /    
|___/_/  /_/ |__/|__/\__,_/_/   \___/  /_____/ |___/\___/_/ /_/\__/  /_/ |_|\____/\__,_/\__/\___/_/
[1;32m[VMware Event Router] 2020/07/01 17:12:45 connecting to Cloud Director https://cloud.o11n.com
[1;35m[VMware Cloud Director] 2020/07/01 17:12:45 Authenticating to Cloud Director https://cloud.o11n.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcee114]

goroutine 1 [running]:
github.com/vmware-samples/vcenter-event-broker-appliance/vmware-event-router/internal/stream.NewCloudDirectorStream(0x1320440, 0xc000039880, 0xc000025d18, 0x6, 0xc000028c40, 0x14, 0xc000028c60, 0x16, 0xc000025d20, 0xd, ...)
	/home/jlew/vcenter-event-broker-appliance/vmware-event-router/internal/stream/clouddirector.go:88 +0xa44
main.main()
	/home/jlew/vcenter-event-broker-appliance/vmware-event-router/cmd/main.go:99 +0x171e
Process exiting with code: 0

**Comment by tschoergez** [comment]
response status code cannot received e.g. if it's a wrong host, DNS problems, network problems to connect to VCD even befure authenticating
